name: Auto-Formatador (Prettier)

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Rodar o Prettier e Commitar
        uses: creyD/prettier_action@v4.3
        with:
          file_pattern: "**/*.html **/*.css"
          
          commit_message: "style: formata o código automaticamente com o Prettier"
